- name: Copy ASGI packit_dashboard.py file
  copy:
    src: /src/packit_dashboard/packit_dashboard.asgi
    dest: /usr/share/packit_dashboard/packit_dashboard.asgi
    mode: 0664

- name: Copy run_httpd.sh
  copy:
    src: /src/files/scripts/run_httpd.sh
    dest: /usr/bin/run_httpd.sh
    mode: 0775
